# Generated by Django 4.0.1 on 2022-02-04 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
