# Generated by Django 4.0.1 on 2022-02-06 06:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
