# Generated by Django 4.0.1 on 2022-02-09 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
