# Generated by Django 4.0.1 on 2022-02-10 12:45

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('min', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0)])),
                ('max', models.IntegerField(default=500, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
