# Generated by Django 4.0.1 on 2022-02-17 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=models.URLField(validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
    ]
