# Generated by Django 4.0.1 on 2022-02-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_productimage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='img',
            field=models.URLField(),
        ),
    ]
