# Generated by Django 4.0.1 on 2022-02-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productimage_img'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricerange',
            unique_together={('min', 'max')},
        ),
    ]
