# Generated by Django 4.0.1 on 2022-02-18 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_pricerange_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
