# Generated by Django 4.0.1 on 2022-02-18 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_promos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promos',
            new_name='Availability',
        ),
    ]
