# Generated by Django 4.0.1 on 2022-02-11 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
