# Generated by Django 3.1.2 on 2022-01-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20220102_1154'),
        ('theatre', '0001_initial'),
        ('showtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie', unique=True),
        ),
        migrations.AlterField(
            model_name='showtime',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.theatre', unique=True),
        ),
    ]
