# Generated by Django 3.1.2 on 2022-01-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
        ('movie', '0009_auto_20220102_1154'),
        ('showtime', '0002_auto_20220102_1225'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='showtime',
            unique_together={('movie', 'theatre')},
        ),
    ]
