# Generated by Django 3.1.2 on 2022-01-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showtime', '0005_auto_20220102_1234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Showtime',
        ),
    ]
