# Generated by Django 3.1.2 on 2022-01-02 12:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movie', '0009_auto_20220102_1154'),
        ('theatre', '0002_remove_theatre_show_times'),
        ('showtime', '0006_delete_showtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_times', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(default='{5:10 pm}'), size=None)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.theatre')),
            ],
        ),
        migrations.AddConstraint(
            model_name='showtime',
            constraint=models.UniqueConstraint(fields=('movie', 'theatre'), name='showtime'),
        ),
    ]
