# Generated by Django 3.1.2 on 2022-01-02 11:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('poster', models.URLField(blank=True, null=True)),
                ('synopsis', models.TextField(blank=True, max_length=2000, null=True)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
