# Generated by Django 3.1.2 on 2022-01-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='details',
            field=models.JSONField(),
        ),
    ]
