# Generated by Django 3.1.2 on 2022-01-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20220102_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='details',
            field=models.JSONField(default={'info': None}),
        ),
    ]
