# Generated by Django 3.1.2 on 2022-01-02 11:28

from django.db import migrations, models
import movie.models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20220102_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='details',
            field=models.JSONField(default=movie.models.get_default_movie_details),
        ),
    ]
